index:
    path: /
    controller: App\Controller\DefaultController::index

blog:
    path: /inscription
    controller: App\Controller\DefaultController::inscription
dashboard: 
    path: /dashboard
    controller: App\Controller\DefaultController::dashboard

# gestpara:
#    path: /gestpara/{id}  #/dashboard/{age}
#   controller: App\Controller\Gestpara::index
#    defaults:
#       id: 0
#    requirements: 
#        id: \d+
#    methods: [POST, GET]
#    host: localhost
#   schemes: [http, https]
