index:
    path: /
    controller: App\Controller\DefaultController::index

inscription:
    path: /inscription
    controller: App\Controller\DefaultController::inscription

dashboard: 
    path: /dashboard
    controller: App\Controller\DefaultController::dashboard

